stages:
  - install
  - build
  - quality

default:
  image: node

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - build/

eslint:
  stage: quality
  script:
    - npm run lint:check
  dependencies:
    - install

prettier:
  stage: quality
  script:
    - npm run prettier:check
  dependencies:
    - install

types:
  stage: quality
  script:
    - npm run types:check
  dependencies:
    - install
